### ISSUE TITLE
How to make a llc360 grid fileds by ourselves?

### ISSUE THREAD

**Issue by liu-ran** [MITgcm-contrib/llc_hires#6]
Hi, I want to run a 0.25-degree global simulation. But I don't find any example for llc360. How to make it by ourselves? Thanks!

**Comment by menemenlis** [comment]
I am sure there are better, more accurate ways for doing this, or maybe someone already has llc360 available, but one way to create an llc360 grid might be to start with the llc1080 grid and grab every third XC/YC and XG/YG.

Alternatively, we have llc270 and llc540 grid definitions ready to go, if one of those two resolutions works for you.

**Comment by liu-ran** [comment]
@menemenlis Thanks! I think it will work from the llc1080 as you said. But how to make the blank list of tiles for the data.exch of llc360?

I understand llc270 and llc540 are ready. But we want to test some parametric work (related to topography) based on a 1/4 degree MITgcm model because the ocean component in the next-gen climate model is 1/4 degree. Thanks again for your suggestions.

**Comment by menemenlis** [comment]
Once you have the grid and the bathymetry (which you could also generate from llc1080 although it’s quite old bathymetry), you can run the model for one time step and get a list of empty tiles in STDOUT file.  See discussion here: http://mailman.mitgcm.org/pipermail/mitgcm-support/2022-November/013314.html <http://mailman.mitgcm.org/pipermail/mitgcm-support/2022-November/013314.html>

**Comment by liu-ran** [comment]
@menemenlis Got it! Many thanks!
