### ISSUE TITLE
how to calculate UXVY from UEVN?

### ISSUE THREAD

**Issue by liu-ran** [MITgcm-contrib/llc_hires#7]
Hi all,

Recently I tried to change the wind stress as the model forcing. However, I didn't find a function to calculate UXVY from UEVN. I can only find the function to calculate UEVN from UXVY but it is only useful in the postprocessing. Could you share any similar experience in calculating UXVY from UEVN? Thanks!

Best,
Ran

**Comment by menemenlis** [comment]
Hi Ran, I just added rotation formula from model to geographical coordinates to
https://github.com/MITgcm-contrib/llc_hires/blob/master/llc_4320/readme_llc4320.txt
Note, however, that if you specify wind stress (or 10-m wind) on a regular lat/lon grid, the rotation from UEVN from UXVY will be done automatically by pkg/exf.
